-- CopeLoot_Data.lua
-- Player wishlist data for CopeLoot
-- Auto-generated from "V+ raid wishlist.xlsx"
-- Each player has up to 3 prioritized wishlist slots.

CopeLoot_PlayerData = {
	{
		name  = "Alexxandros",
		class = "Unknown",
		wish1 = "Dark Heart Pants",
		wish2 = "Grizzly Fur Pelerine",
		wish3 = "Heavy Dark Iron Ring",
	},
	{
		name  = "Altdorf",
		class = "Unknown",
		wish1 = "Reactive Auto-Recaster (Questhero)",
		wish2 = "Maladath (Ronald)",
		wish3 = "Bonereaver's Edge (Ronald)",
	},
	{
		name  = "Antikvar",
		class = "Unknown",
		wish1 = "Ashjre'thul, Crossbow of Smiting",
		wish2 = "Shadowstrike",
		wish3 = "Charred Tunic",
	},
	{
		name  = "Ascended",
		class = "Unknown",
		wish1 = "The Untamed Blade",
		wish2 = "Blazefury Medallion",
		wish3 = "Shard of the Flame",
	},
	{
		name  = "Ashdeena",
		class = "Unknown",
		wish1 = "Elementium Reinforced Bulwark",
		wish2 = "Ashkandi",
		wish3 = "Elementium Echo Modulator",
	},
	{
		name  = "Bangy",
		class = "Unknown",
		wish1 = "",
		wish2 = "Quick Strike Ring (Maggy)",
		wish3 = "Deathbringer (Moonglave)",
	},
	{
		name  = "Bax",
		class = "Unknown",
		wish1 = "Drake Fang Talisman",
		wish2 = "Band of Accuria",
		wish3 = "Maladath",
	},
	{
		name  = "Blindcripple",
		class = "Unknown",
		wish1 = "Ring of Suffering",
		wish2 = "Puissant Cape",
		wish3 = "Sharp Bone of the Sand Reaver",
	},
	{
		name  = "Boudan",
		class = "Unknown",
		wish1 = "Drake Fang Talisman",
		wish2 = "Sawtooth Talisman",
		wish3 = "",
	},
	{
		name  = "Cassandra",
		class = "Unknown",
		wish1 = "Rejuvenating Gem",
		wish2 = "Pure Elementium Band",
		wish3 = "Shroud of Pure Thought",
	},
	{
		name  = "Castaspela",
		class = "Unknown",
		wish1 = "Rejuvenating Gem",
		wish2 = "Ring of the Diplomat",
		wish3 = "Melted Breastplate",
	},
	{
		name  = "Chocolanza",
		class = "Unknown",
		wish1 = "Idol of Wilderness",
		wish2 = "Sawtooth Talisman",
		wish3 = "Drake Fang Talisman",
	},
	{
		name  = "Clycer",
		class = "Unknown",
		wish1 = "Claw of Molten Fury",
		wish2 = "",
		wish3 = "Puissant Cape",
	},
	{
		name  = "Coldblood",
		class = "Unknown",
		wish1 = "Demonic Claw",
		wish2 = "",
		wish3 = "Fiery Claws",
	},
	{
		name  = "Cremation",
		class = "Unknown",
		wish1 = "Dragon's Touch",
		wish2 = "Band of Forced Concentration",
		wish3 = "Ring of Entropy",
	},
	{
		name  = "Cyclones",
		class = "Unknown",
		wish1 = "",
		wish2 = "Hederine Shackles",
		wish3 = "Spiked Caraspace Fragment",
	},
	{
		name  = "Esparanta",
		class = "Unknown",
		wish1 = "Snowblind Shoes",
		wish2 = "Gloves of Delusional Power",
		wish3 = "Shard of the Scale",
	},
	{
		name  = "Folle",
		class = "Unknown",
		wish1 = "The Untamed Blade",
		wish2 = "Melted Bindings",
		wish3 = "Molten Grips",
	},
	{
		name  = "Franshals",
		class = "Unknown",
		wish1 = "",
		wish2 = "Dragon's Touch",
		wish3 = "Fang of the Mystics",
	},
	{
		name  = "Gendirector",
		class = "Unknown",
		wish1 = "Sawtooth Talisman (Eggmorphing)",
		wish2 = "Drake Fang Talisman (Eggmorphing)",
		wish3 = "Ring of Master [Maces] (Eggmorphing)",
	},
	{
		name  = "Gnomosek",
		class = "Unknown",
		wish1 = "Neltharion's Tear",
		wish2 = "Ashes of Destruction",
		wish3 = "Staff of the Shadow Flame",
	},
	{
		name  = "Goodmorning",
		class = "Unknown",
		wish1 = "Staff of the Shadow Flame",
		wish2 = "",
		wish3 = "",
	},
	{
		name  = "Hsaru",
		class = "Unknown",
		wish1 = "Ashkandi",
		wish2 = "Crul'shorukh, Edge of Chaos",
		wish3 = "Ring of Master [Fists]",
	},
	{
		name  = "Imbaladin",
		class = "Unknown",
		wish1 = "Melted Breastplate",
		wish2 = "Drake Talon Cleaver",
		wish3 = "Lashlayer's Signet",
	},
	{
		name  = "Iridium",
		class = "Unknown",
		wish1 = "Drake Fang Talisman",
		wish2 = "Prestor's Talisman of Connivery",
		wish3 = "Aged Core Leather Gloves [Swords]",
	},
	{
		name  = "Itron",
		class = "Unknown",
		wish1 = "Band of Accuria",
		wish2 = "Sawtooth Talisman",
		wish3 = "Head of Nefarian [H]",
	},
	{
		name  = "Kamazxx",
		class = "Unknown",
		wish1 = "Onslaught Girdle",
		wish2 = "Lashlayer's Signet",
		wish3 = "Molten Grips",
	},
	{
		name  = "Karyn",
		class = "Unknown",
		wish1 = "Elementium Echo Modulator",
		wish2 = "Styleen's Impeding Scarab",
		wish3 = "Hypergear (Karyn)",
	},
	{
		name  = "Khanviction",
		class = "Unknown",
		wish1 = "Band of Accuria (Khanviction)",
		wish2 = "Grizzly Fur Peleine",
		wish3 = "",
	},
	{
		name  = "Kicker",
		class = "Unknown",
		wish1 = "Ring of Accuria",
		wish2 = "Hederine Shackles",
		wish3 = "Perdition's Blade",
	},
	{
		name  = "Krein",
		class = "Unknown",
		wish1 = "Boots of the Shadow Flame",
		wish2 = "Ring of Master [Fists]",
		wish3 = "Aged Core Leather Gloves [Fists]",
	},
	{
		name  = "Kreyvon",
		class = "Unknown",
		wish1 = "Signet of Unlimited Power (Lleeggiioonn)",
		wish2 = "Claw of Molten Fury (Kreyvon)",
		wish3 = "Charred Tunic (Kalipso)",
	},
	{
		name  = "Kukuruza",
		class = "Unknown",
		wish1 = "Reactive Auto-Recaster",
		wish2 = "Shroud of the Supreme",
		wish3 = "",
	},
	{
		name  = "Lazard",
		class = "Unknown",
		wish1 = "Deathbringer",
		wish2 = "Melted Helmet",
		wish3 = "Puissant Cape",
	},
	{
		name  = "Lokiy",
		class = "Unknown",
		wish1 = "Neltharion's Tear",
		wish2 = "Ancient Petrified Leaf",
		wish3 = "",
	},
	{
		name  = "Lutherening",
		class = "Unknown",
		wish1 = "Fist of Molten Fury",
		wish2 = "Drake Fang Talisman",
		wish3 = "Lashlayer's Signet",
	},
	{
		name  = "Maevis",
		class = "Unknown",
		wish1 = "Drake Fang Talisman (Egdod)",
		wish2 = "Band of Accuria (Egdod)",
		wish3 = "Ring of Suffering (Egdod)",
	},
	{
		name  = "Malavon",
		class = "Unknown",
		wish1 = "Chromatically Tempered Sword",
		wish2 = "",
		wish3 = "",
	},
	{
		name  = "Minkie",
		class = "Unknown",
		wish1 = "Pure Elementium Band",
		wish2 = "Rejuvenating Gem",
		wish3 = "Shimmering Geta",
	},
	{
		name  = "Mokhra",
		class = "Unknown",
		wish1 = "Crul'shorukh, Edge of Chaos",
		wish2 = "Striker's Mark",
		wish3 = "Drake Fang Talisman",
	},
	{
		name  = "Molkerei",
		class = "Unknown",
		wish1 = "Elementium Reinforced Bulwark",
		wish2 = "Styleen's Impeding Scarab",
		wish3 = "Onyxia Hide Backpack",
	},
	{
		name  = "Morgravez",
		class = "Unknown",
		wish1 = "Ashkandi",
		wish2 = "",
		wish3 = "Lashlayer's Signet",
	},
	{
		name  = "Necriel",
		class = "Unknown",
		wish1 = "Sawtooth Talisman",
		wish2 = "Maladath",
		wish3 = "Ashkandi",
	},
	{
		name  = "Nobuddy",
		class = "Unknown",
		wish1 = "Hederine Shackles",
		wish2 = "Ring of Suffering",
		wish3 = "Blazefury Medallion (Hy)",
	},
	{
		name  = "Norppa",
		class = "Unknown",
		wish1 = "Crul'shorukh, Edge of Chaos (Norppa)",
		wish2 = "Fist of Molten Fury (Norppa)",
		wish3 = "Barbed Choker (Norppa)",
	},
	{
		name  = "Oleforsby",
		class = "Unknown",
		wish1 = "Melted Breastplate",
		wish2 = "Melted Bindings",
		wish3 = "Choker of the Fire Lord",
	},
	{
		name  = "Orah",
		class = "Unknown",
		wish1 = "Everhot Choker",
		wish2 = "",
		wish3 = "",
	},
	{
		name  = "Xaoc",
		class = "Unknown",
		wish1 = "Staff of the Shadow Flame",
		wish2 = "Neltharion's Tear",
		wish3 = "Dragon's Touch",
	},
	{
		name  = "Paincuck",
		class = "Unknown",
		wish1 = "Shroud of the Supreme",
		wish2 = "Blacklight Bracer",
		wish3 = "Snowblind Shoes",
	},
	{
		name  = "Passim",
		class = "Unknown",
		wish1 = "",
		wish2 = "Reactive Auto-Recaster",
		wish3 = "Styleen's Impeding Scarab",
	},
	{
		name  = "Pricklypear",
		class = "Unknown",
		wish1 = "The Untamed Blade (Pricklypear)",
		wish2 = "Melted Helmet",
		wish3 = "Melted Legplates",
	},
	{
		name  = "Qox",
		class = "Unknown",
		wish1 = "Choker of the Fire Lord",
		wish2 = "Hot Claws",
		wish3 = "Burnt Bindings",
	},
	{
		name  = "Ratso",
		class = "Unknown",
		wish1 = "",
		wish2 = "Firemaw's Clutch",
		wish3 = "Elementium Echo Modulator",
	},
	{
		name  = "Rheedd",
		class = "Unknown",
		wish1 = "Ashjre'thul, Crossbow of Smiting",
		wish2 = "Shadowstrike",
		wish3 = "Quick Strike Ring",
	},
	{
		name  = "Rist",
		class = "Unknown",
		wish1 = "Neltharion's Tear",
		wish2 = "Pure Elementium Band",
		wish3 = "",
	},
	{
		name  = "Sathite",
		class = "Unknown",
		wish1 = "",
		wish2 = "",
		wish3 = "Combat Parser Interface V150r",
	},
	{
		name  = "Scyn",
		class = "Unknown",
		wish1 = "Staff of the Shadow Flame",
		wish2 = "Soul Shard Pendant",
		wish3 = "Petrified Scarab (Scyn)",
	},
	{
		name  = "Sewerslvt",
		class = "Unknown",
		wish1 = "Ring of Suffering",
		wish2 = "Barbed Choker",
		wish3 = "Doomhide Gauntlets",
	},
	{
		name  = "Shankerella",
		class = "Unknown",
		wish1 = "Band of Accuria",
		wish2 = "Deathbringer",
		wish3 = "Crul'shorukh, Edge of Chaos",
	},
	{
		name  = "Sieghadin",
		class = "Unknown",
		wish1 = "Azuresong Mageblade",
		wish2 = "Shroud of the Supreme",
		wish3 = "Blacklight Bracer",
	},
	{
		name  = "Tepate",
		class = "Unknown",
		wish1 = "",
		wish2 = "Melted Legplates",
		wish3 = "",
	},
	{
		name  = "Tirohtar",
		class = "Unknown",
		wish1 = "Obsidian Edged Blade",
		wish2 = "Melted Bindings",
		wish3 = "Molten Grips",
	},
	{
		name  = "Tolkushka",
		class = "Unknown",
		wish1 = "Pure Elementium Band (Kocherga)",
		wish2 = "Shimmering Geta",
		wish3 = "Seal of the Archmagus (Tolkushka)",
	},
	{
		name  = "Wernerherzog",
		class = "Unknown",
		wish1 = "Styleen's Impeding Scarab",
		wish2 = "Empyrean Demolisher",
		wish3 = "Melted Helmet",
	},
	{
		name  = "Wonderboy",
		class = "Unknown",
		wish1 = "Reactive Auto-Recaster",
		wish2 = "Shroud of the Supreme",
		wish3 = "Staff of the Shadow Flame",
	},
	{
		name  = "Xykyta",
		class = "Unknown",
		wish1 = "Empyrean Demolisher",
		wish2 = "Ring of Master [1h Mace]",
		wish3 = "Combat Parser Interface V150r",
	},
	{
		name  = "Yasuke",
		class = "Unknown",
		wish1 = "Drake Fang Talisman (Yasuke)",
		wish2 = "Prestor's Talisman of Connivery (Yasuke)",
		wish3 = "Ring of Suffering (Yasuke)",
	},
	{
		name  = "Yobachidu",
		class = "Unknown",
		wish1 = "Onyxia Hide Backpack",
		wish2 = "Toughened Silithid Hide Gloves",
		wish3 = "Medallion of Steadfast Might (pass tank)",
	},
	{
		name  = "Zankz",
		class = "Unknown",
		wish1 = "Chronomirage",
		wish2 = "Personal Harm Prevention Field Emitter",
		wish3 = "Drake Fang Talisman",
	},
	{
		name  = "Zibazoo",
		class = "Unknown",
		wish1 = "Band of Accuria (Tazdingi)",
		wish2 = "Ring of Suffering (Tazdingi)",
		wish3 = "Shadowstrike (Tazdingi)",
	},
}

-- Single reserve item per player
CopeLoot_ReserveData = {
	{ name = "Amoroso", class = "Unknown", boss = "Arlokk", reserve = "Panther Hide Sack", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Apacha", class = "Unknown", boss = "Jin'do", reserve = "Overlord's Embrace", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Ascended", class = "Unknown", boss = "Arlokk", reserve = "Overlord's Onyx Band", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Bankofboudan", class = "Unknown", boss = "Thekal", reserve = "Swift Zulian Tiger", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Bax", class = "Unknown", boss = "Other", reserve = "Bijou", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Baxul", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Beautlock", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Bag of Whammies", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Beefoo", class = "Unknown", boss = "Mandokir", reserve = "Warblade of the Hakkari(OH)", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Bonedolier", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Bag of Whammies", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Boudan", class = "Unknown", boss = "Azus", reserve = "Golden Ceremonial Bloodletter (MH)", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Cassandra", class = "Unknown", boss = "Arlokk", reserve = "Panther Hide Sack", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Castaspela", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Evil Eye", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Ccb", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Chachakka", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Bag of Whammies", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Chocolanza", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Cliffer", class = "Unknown", boss = "Mandokir", reserve = "Zanzil's Seal", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Clycer", class = "Unknown", boss = "Venoxis", reserve = "Zulian Tigerhide Cloak", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Corz", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Bag of Whammies", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Cremation", class = "Unknown", boss = "Gahz'ranka", reserve = "Nat Pagle's Broken Reel", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Cuckoo", class = "Unknown", boss = "Mandokir", reserve = "Primalist's Seal", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Deathinjune", class = "Unknown", boss = "Hakkar", reserve = "Ancient Hakkari Manslayer", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Denacost", class = "Unknown", boss = "Venoxis", reserve = "Zanzil's Band", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Dixie", class = "Unknown", boss = "Hakkar", reserve = "Aegis of the Blood God", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Dotterific", class = "Unknown", boss = "Mandokir", reserve = "Zanzil's Seal", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Dragora", class = "Unknown", boss = "Thekal", reserve = "Swift Zulian Tiger", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Druiderella", class = "Unknown", boss = "Arlokk", reserve = "Will of Arlokk", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Dwarfission", class = "Unknown", boss = "Mandokir", reserve = "Halberd of Smiting", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Eggmorphing", class = "Unknown", boss = "Azus", reserve = "Golden Ceremonial Bloodletter (MH)", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Fastfoodz", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Folle", class = "Unknown", boss = "Hakkar", reserve = "Zin'rokh, Destroyer of World", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Franshals", class = "Unknown", boss = "Mar'li", reserve = "Marli's Touch", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Frostynewbie", class = "Unknown", boss = "Mandokir", reserve = "Zanzil's Seal", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Garmosh", class = "Unknown", boss = "Azus", reserve = "Azus' Arrow Launcher", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Gendirector", class = "Unknown", boss = "Azus", reserve = "Mark of Thirst", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Gnomage", class = "Unknown", boss = "Hakkar", reserve = "Cloak of Consumption", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Goodmorning", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Gronn", class = "Unknown", boss = "Hakkar", reserve = "Aegis of the Blood God", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Halmar", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Evil Eye", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Hdrezka", class = "Unknown", boss = "Mandokir", reserve = "Bloodlord's Defender", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Heckate", class = "Unknown", boss = "Mandokir", reserve = "Halberd of Smiting", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Hsaru", class = "Unknown", boss = "Thekal", reserve = "Swift Zulian Tiger", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Imbaladin", class = "Unknown", boss = "Hermit", reserve = "Relic Cleaver", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Itron", class = "Unknown", boss = "Azus", reserve = "Mark of Thirst", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Jassy", class = "Unknown", boss = "Other", reserve = "Bijou", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Kamazxx", class = "Unknown", boss = "Mandokir", reserve = "Halberd of Smiting", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Karelappel", class = "Unknown", boss = "Hakkar", reserve = "Aegis of the Blood God", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Karyn", class = "Unknown", boss = "Thekal", reserve = "Swift Zulian Tiger", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Khanviction", class = "Unknown", boss = "Arlokk", reserve = "Overlord's Onyx Band", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Kicker", class = "Unknown", boss = "Hakkar", reserve = "Heart of Hakkar", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Kouli", class = "Unknown", boss = "Arlokk", reserve = "Overlord's Onyx Band", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Krein", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = true, wushoolay = false } },
	{ name = "Laz", class = "Unknown", boss = "Hakkar", reserve = "Cloak of Consumption", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Loveandwar", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Evil Eye", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Lovedeath", class = "Unknown", boss = "Hakkar", reserve = "Zin'rokh, Destroyer of World", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Lutherening", class = "Unknown", boss = "Jin'do", reserve = "Overlord's Embrace", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Macho", class = "Unknown", boss = "Hakkar", reserve = "Zin'rokh, Destroyer of World", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Malakos", class = "Unknown", boss = "Hakkar", reserve = "The Eye of Hakkar", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Marxx", class = "Unknown", boss = "Thekal", reserve = "Seal of Jin", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Mcgonagall", class = "Unknown", boss = "Mandokir", reserve = "Swift Razzashi Raptor", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Minkie", class = "Unknown", boss = "Azus", reserve = "Berserker Blood Sample", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Mokhra", class = "Unknown", boss = "Azus", reserve = "Golden Ceremonial Bloodletter (OH)", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Molkerei", class = "Unknown", boss = "Arlokk", reserve = "Overlord's Onyx Band", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Moonglave", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Naheul", class = "Unknown", boss = "Mar'li", reserve = "Band of Jin", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Naprimer", class = "Unknown", boss = "Azus", reserve = "Helm of Sacrifice", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Nettle", class = "Unknown", boss = "Hakkar", reserve = "Cloak of Consumption", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Norppa", class = "Unknown", boss = "Azus", reserve = "Golden Ceremonial Bloodletter (OH)", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Oblivion", class = "Unknown", boss = "Madness", reserve = "Trinket Component (0/4)", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Oleforsby", class = "Unknown", boss = "Hakkar", reserve = "Ancient Hakkari Manslayer", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Orah", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Evil Eye", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Orcitoslocos", class = "Unknown", boss = "Thekal", reserve = "Thekal's Grasp", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Outsane", class = "Unknown", boss = "Hermit", reserve = "Old Calico Hood", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Paincuck", class = "Unknown", boss = "Thekal", reserve = "Betrayer's Boots", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Palmetto", class = "Unknown", boss = "Venoxis", reserve = "Zanzil's Band", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Partigiano", class = "Unknown", boss = "Thekal", reserve = "Swift Zulian Tiger", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Passim", class = "Unknown", boss = "Other", reserve = "Bijou", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Plaque", class = "Unknown", boss = "Jeklik", reserve = "Primalist's Band", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Pricklypear", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Ragemage", class = "Unknown", boss = "Hakkar", reserve = "Bloodcaller", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Ratso", class = "Unknown", boss = "Thekal", reserve = "Swift Zulian Tiger", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Raynn", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Evil Eye", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Rearpoker", class = "Unknown", boss = "Mar'li", reserve = "Band of Jin", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Rheedd", class = "Unknown", boss = "Azus", reserve = "Mark of Thirst", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Sadsun", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Judgement", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Sarc", class = "Unknown", boss = "Other", reserve = "Blooddrenched Mask", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Sathite", class = "Unknown", boss = "Azus", reserve = "Golden Ceremonial Bloodletter (OH)", trinkets = { grilek = false, hazzarah = false, renataki = true, wushoolay = false } },
	{ name = "Selenana", class = "Unknown", boss = "Azus", reserve = "Berserker Blood Sample", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Serbius", class = "Unknown", boss = "Azus", reserve = "Azus' Arrow Launcher", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Sincinnsin", class = "Unknown", boss = "Mar'li", reserve = "Band of Jin", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Sonush", class = "Unknown", boss = "Jin'do", reserve = "Jin'do's Evil Eye", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Sosah", class = "Unknown", boss = "Thekal", reserve = "Seal of Jin", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Steals", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Tepate", class = "Unknown", boss = "Azus", reserve = "Berserker Blood Sample", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Tepka", class = "Unknown", boss = "Hakkar", reserve = "Ancient Hakkari Manslayer", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Tolkushka", class = "Unknown", boss = "Mar'li", reserve = "Band of Jin", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Tosco", class = "Unknown", boss = "Thekal", reserve = "Thekal's Grasp", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Trekoer", class = "Unknown", boss = "Hakkar", reserve = "Ancient Hakkari Manslayer", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Tuhar", class = "Unknown", boss = "Jin'do", reserve = "Overlord's Embrace", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Ubetraydalaw", class = "Unknown", boss = "Jeklik", reserve = "Primalist's Band", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Ufodriver", class = "Unknown", boss = "Azus", reserve = "Azus' Arrow Launcher", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Vendormage", class = "Unknown", boss = "Venoxis", reserve = "Zanzil's Band", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Verandan", class = "Unknown", boss = "Venoxis", reserve = "Fang of Venoxis", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Verzu", class = "Unknown", boss = "Hakkar", reserve = "Cloak of Consumption", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Wernerherzog", class = "Unknown", boss = "Arlokk", reserve = "Panther Hide Sack", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Willingtodie", class = "Unknown", boss = "Gahz'ranka", reserve = "Nat Pagle's Broken Reel", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Wizdom", class = "Unknown", boss = "Mandokir", reserve = "Swift Razzashi Raptor", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Xalton", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Xykyta", class = "Unknown", boss = "Hakkar", reserve = "Aegis of the Blood God", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Ygor", class = "Unknown", boss = "Azus", reserve = "Azus' Arrow Launcher", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Yobachidu", class = "Unknown", boss = "Other", reserve = "Idol", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Zankz", class = "Unknown", boss = "Azus", reserve = "Azus' Arrow Launcher", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Zeezee", class = "Unknown", boss = "Hakkar", reserve = "Cloak of Consumption", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Zibadin", class = "Unknown", boss = "Hakkar", reserve = "Ancient Hakkari Manslayer", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Zloun", class = "Unknown", boss = "Mar'li", reserve = "Band of Jin", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Zolgend", class = "Unknown", boss = "Thekal", reserve = "Swift Zulian Tiger", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
	{ name = "Zoorro", class = "Unknown", boss = "Thekal", reserve = "Swift Zulian Tiger", trinkets = { grilek = false, hazzarah = false, renataki = false, wushoolay = false } },
}