-- CopeLoot_Data.lua
-- Player wishlist data for CopeLoot
-- Auto-generated from "V+ raid wishlist.xlsx"
-- Each player has up to 3 prioritized wishlist slots.

CopeLoot_PlayerData = {
	{
		name  = "Alexxandros",
		class = "Unknown",
		wish1 = "Dark Heart Pants",
		wish2 = "Grizzly Fur Pelerine",
		wish3 = "Heavy Dark Iron Ring",
	},
	{
		name  = "Altdorf",
		class = "Unknown",
		wish1 = "Reactive Auto-Recaster (Questhero)",
		wish2 = "Maladath (Ronald)",
		wish3 = "Bonereaver's Edge (Ronald)",
	},
	{
		name  = "Antikvar",
		class = "Unknown",
		wish1 = "Ashjre'thul, Crossbow of Smiting",
		wish2 = "Shadowstrike",
		wish3 = "Charred Tunic",
	},
	{
		name  = "Ascended",
		class = "Unknown",
		wish1 = "The Untamed Blade",
		wish2 = "Blazefury Medallion",
		wish3 = "Shard of the Flame",
	},
	{
		name  = "Ashdeena",
		class = "Unknown",
		wish1 = "Elementium Reinforced Bulwark",
		wish2 = "Ashkandi",
		wish3 = "Elementium Echo Modulator",
	},
	{
		name  = "Bangy",
		class = "Unknown",
		wish1 = "",
		wish2 = "Quick Strike Ring (Maggy)",
		wish3 = "Deathbringer (Moonglave)",
	},
	{
		name  = "Bax",
		class = "Unknown",
		wish1 = "Drake Fang Talisman",
		wish2 = "Band of Accuria",
		wish3 = "Maladath",
	},
	{
		name  = "Blindcripple",
		class = "Unknown",
		wish1 = "Ring of Suffering",
		wish2 = "Puissant Cape",
		wish3 = "Sharp Bone of the Sand Reaver",
	},
	{
		name  = "Boudan",
		class = "Unknown",
		wish1 = "Drake Fang Talisman",
		wish2 = "Sawtooth Talisman",
		wish3 = "",
	},
	{
		name  = "Cassandra",
		class = "Unknown",
		wish1 = "Rejuvenating Gem",
		wish2 = "Pure Elementium Band",
		wish3 = "Shroud of Pure Thought",
	},
	{
		name  = "Castaspela",
		class = "Unknown",
		wish1 = "Rejuvenating Gem",
		wish2 = "Ring of the Diplomat",
		wish3 = "Melted Breastplate",
	},
	{
		name  = "Chocolanza",
		class = "Unknown",
		wish1 = "Idol of Wilderness",
		wish2 = "Sawtooth Talisman",
		wish3 = "Drake Fang Talisman",
	},
	{
		name  = "Clycer",
		class = "Unknown",
		wish1 = "Claw of Molten Fury",
		wish2 = "",
		wish3 = "Puissant Cape",
	},
	{
		name  = "Coldblood",
		class = "Unknown",
		wish1 = "Demonic Claw",
		wish2 = "",
		wish3 = "Fiery Claws",
	},
	{
		name  = "Cremation",
		class = "Unknown",
		wish1 = "Dragon's Touch",
		wish2 = "Band of Forced Concentration",
		wish3 = "Ring of Entropy",
	},
	{
		name  = "Cyclones",
		class = "Unknown",
		wish1 = "",
		wish2 = "Hederine Shackles",
		wish3 = "Spiked Caraspace Fragment",
	},
	{
		name  = "Esparanta",
		class = "Unknown",
		wish1 = "Snowblind Shoes",
		wish2 = "Gloves of Delusional Power",
		wish3 = "Shard of the Scale",
	},
	{
		name  = "Folle",
		class = "Unknown",
		wish1 = "The Untamed Blade",
		wish2 = "Melted Bindings",
		wish3 = "Molten Grips",
	},
	{
		name  = "Franshals",
		class = "Unknown",
		wish1 = "",
		wish2 = "Dragon's Touch",
		wish3 = "Fang of the Mystics",
	},
	{
		name  = "Gendirector",
		class = "Unknown",
		wish1 = "Sawtooth Talisman (Eggmorphing)",
		wish2 = "Drake Fang Talisman (Eggmorphing)",
		wish3 = "Ring of Master [Maces] (Eggmorphing)",
	},
	{
		name  = "Gnomosek",
		class = "Unknown",
		wish1 = "Neltharion's Tear",
		wish2 = "Ashes of Destruction",
		wish3 = "Staff of the Shadow Flame",
	},
	{
		name  = "Goodmorning",
		class = "Unknown",
		wish1 = "Staff of the Shadow Flame",
		wish2 = "",
		wish3 = "",
	},
	{
		name  = "Hsaru",
		class = "Unknown",
		wish1 = "Ashkandi",
		wish2 = "Crul'shorukh, Edge of Chaos",
		wish3 = "Ring of Master [Fists]",
	},
	{
		name  = "Imbaladin",
		class = "Unknown",
		wish1 = "Melted Breastplate",
		wish2 = "Drake Talon Cleaver",
		wish3 = "Lashlayer's Signet",
	},
	{
		name  = "Iridium",
		class = "Unknown",
		wish1 = "Drake Fang Talisman",
		wish2 = "Prestor's Talisman of Connivery",
		wish3 = "Aged Core Leather Gloves [Swords]",
	},
	{
		name  = "Itron",
		class = "Unknown",
		wish1 = "Band of Accuria",
		wish2 = "Sawtooth Talisman",
		wish3 = "Head of Nefarian [H]",
	},
	{
		name  = "Kamazxx",
		class = "Unknown",
		wish1 = "Onslaught Girdle",
		wish2 = "Lashlayer's Signet",
		wish3 = "Molten Grips",
	},
	{
		name  = "Karyn",
		class = "Unknown",
		wish1 = "Elementium Echo Modulator",
		wish2 = "Styleen's Impeding Scarab",
		wish3 = "Hypergear (Karyn)",
	},
	{
		name  = "Khanviction",
		class = "Unknown",
		wish1 = "Band of Accuria (Khanviction)",
		wish2 = "Grizzly Fur Peleine",
		wish3 = "",
	},
	{
		name  = "Kicker",
		class = "Unknown",
		wish1 = "Ring of Accuria",
		wish2 = "Hederine Shackles",
		wish3 = "Perdition's Blade",
	},
	{
		name  = "Krein",
		class = "Unknown",
		wish1 = "Boots of the Shadow Flame",
		wish2 = "Ring of Master [Fists]",
		wish3 = "Aged Core Leather Gloves [Fists]",
	},
	{
		name  = "Kreyvon",
		class = "Unknown",
		wish1 = "Signet of Unlimited Power (Lleeggiioonn)",
		wish2 = "Claw of Molten Fury (Kreyvon)",
		wish3 = "Charred Tunic (Kalipso)",
	},
	{
		name  = "Kukuruza",
		class = "Unknown",
		wish1 = "Reactive Auto-Recaster",
		wish2 = "Shroud of the Supreme",
		wish3 = "",
	},
	{
		name  = "Lazard",
		class = "Unknown",
		wish1 = "Deathbringer",
		wish2 = "Melted Helmet",
		wish3 = "Puissant Cape",
	},
	{
		name  = "Lokiy",
		class = "Unknown",
		wish1 = "Neltharion's Tear",
		wish2 = "Ancient Petrified Leaf",
		wish3 = "",
	},
	{
		name  = "Lutherening",
		class = "Unknown",
		wish1 = "Fist of Molten Fury",
		wish2 = "Drake Fang Talisman",
		wish3 = "Lashlayer's Signet",
	},
	{
		name  = "Maevis",
		class = "Unknown",
		wish1 = "Drake Fang Talisman (Egdod)",
		wish2 = "Band of Accuria (Egdod)",
		wish3 = "Ring of Suffering (Egdod)",
	},
	{
		name  = "Malavon",
		class = "Unknown",
		wish1 = "Chromatically Tempered Sword",
		wish2 = "",
		wish3 = "",
	},
	{
		name  = "Minkie",
		class = "Unknown",
		wish1 = "Pure Elementium Band",
		wish2 = "Rejuvenating Gem",
		wish3 = "Shimmering Geta",
	},
	{
		name  = "Mokhra",
		class = "Unknown",
		wish1 = "Crul'shorukh, Edge of Chaos",
		wish2 = "Striker's Mark",
		wish3 = "Drake Fang Talisman",
	},
	{
		name  = "Molkerei",
		class = "Unknown",
		wish1 = "Elementium Reinforced Bulwark",
		wish2 = "Styleen's Impeding Scarab",
		wish3 = "Onyxia Hide Backpack",
	},
	{
		name  = "Morgravez",
		class = "Unknown",
		wish1 = "Ashkandi",
		wish2 = "",
		wish3 = "Lashlayer's Signet",
	},
	{
		name  = "Necriel",
		class = "Unknown",
		wish1 = "Sawtooth Talisman",
		wish2 = "Maladath",
		wish3 = "Ashkandi",
	},
	{
		name  = "Nobuddy",
		class = "Unknown",
		wish1 = "Hederine Shackles",
		wish2 = "Ring of Suffering",
		wish3 = "Blazefury Medallion (Hy)",
	},
	{
		name  = "Norppa",
		class = "Unknown",
		wish1 = "Crul'shorukh, Edge of Chaos (Norppa)",
		wish2 = "Fist of Molten Fury (Norppa)",
		wish3 = "Barbed Choker (Norppa)",
	},
	{
		name  = "Oleforsby",
		class = "Unknown",
		wish1 = "Melted Breastplate",
		wish2 = "Melted Bindings",
		wish3 = "Choker of the Fire Lord",
	},
	{
		name  = "Orah",
		class = "Unknown",
		wish1 = "Everhot Choker",
		wish2 = "",
		wish3 = "",
	},
	{
		name  = "Xaoc",
		class = "Unknown",
		wish1 = "Staff of the Shadow Flame",
		wish2 = "Neltharion's Tear",
		wish3 = "Dragon's Touch",
	},
	{
		name  = "Paincuck",
		class = "Unknown",
		wish1 = "Shroud of the Supreme",
		wish2 = "Blacklight Bracer",
		wish3 = "Snowblind Shoes",
	},
	{
		name  = "Passim",
		class = "Unknown",
		wish1 = "",
		wish2 = "Reactive Auto-Recaster",
		wish3 = "Styleen's Impeding Scarab",
	},
	{
		name  = "Pricklypear",
		class = "Unknown",
		wish1 = "The Untamed Blade (Pricklypear)",
		wish2 = "Melted Helmet",
		wish3 = "Melted Legplates",
	},
	{
		name  = "Qox",
		class = "Unknown",
		wish1 = "Choker of the Fire Lord",
		wish2 = "Hot Claws",
		wish3 = "Burnt Bindings",
	},
	{
		name  = "Ratso",
		class = "Unknown",
		wish1 = "",
		wish2 = "Firemaw's Clutch",
		wish3 = "Elementium Echo Modulator",
	},
	{
		name  = "Rheedd",
		class = "Unknown",
		wish1 = "Ashjre'thul, Crossbow of Smiting",
		wish2 = "Shadowstrike",
		wish3 = "Quick Strike Ring",
	},
	{
		name  = "Rist",
		class = "Unknown",
		wish1 = "Neltharion's Tear",
		wish2 = "Pure Elementium Band",
		wish3 = "",
	},
	{
		name  = "Sathite",
		class = "Unknown",
		wish1 = "",
		wish2 = "",
		wish3 = "Combat Parser Interface V150r",
	},
	{
		name  = "Scyn",
		class = "Unknown",
		wish1 = "Staff of the Shadow Flame",
		wish2 = "Soul Shard Pendant",
		wish3 = "Petrified Scarab (Scyn)",
	},
	{
		name  = "Sewerslvt",
		class = "Unknown",
		wish1 = "Ring of Suffering",
		wish2 = "Barbed Choker",
		wish3 = "Doomhide Gauntlets",
	},
	{
		name  = "Shankerella",
		class = "Unknown",
		wish1 = "Band of Accuria",
		wish2 = "Deathbringer",
		wish3 = "Crul'shorukh, Edge of Chaos",
	},
	{
		name  = "Sieghadin",
		class = "Unknown",
		wish1 = "Azuresong Mageblade",
		wish2 = "Shroud of the Supreme",
		wish3 = "Blacklight Bracer",
	},
	{
		name  = "Tepate",
		class = "Unknown",
		wish1 = "",
		wish2 = "Melted Legplates",
		wish3 = "",
	},
	{
		name  = "Tirohtar",
		class = "Unknown",
		wish1 = "Obsidian Edged Blade",
		wish2 = "Melted Bindings",
		wish3 = "Molten Grips",
	},
	{
		name  = "Tolkushka",
		class = "Unknown",
		wish1 = "Pure Elementium Band (Kocherga)",
		wish2 = "Shimmering Geta",
		wish3 = "Seal of the Archmagus (Tolkushka)",
	},
	{
		name  = "Wernerherzog",
		class = "Unknown",
		wish1 = "Styleen's Impeding Scarab",
		wish2 = "Empyrean Demolisher",
		wish3 = "Melted Helmet",
	},
	{
		name  = "Wonderboy",
		class = "Unknown",
		wish1 = "Reactive Auto-Recaster",
		wish2 = "Shroud of the Supreme",
		wish3 = "Staff of the Shadow Flame",
	},
	{
		name  = "Xykyta",
		class = "Unknown",
		wish1 = "Empyrean Demolisher",
		wish2 = "Ring of Master [1h Mace]",
		wish3 = "Combat Parser Interface V150r",
	},
	{
		name  = "Yasuke",
		class = "Unknown",
		wish1 = "Drake Fang Talisman (Yasuke)",
		wish2 = "Prestor's Talisman of Connivery (Yasuke)",
		wish3 = "Ring of Suffering (Yasuke)",
	},
	{
		name  = "Yobachidu",
		class = "Unknown",
		wish1 = "Onyxia Hide Backpack",
		wish2 = "Toughened Silithid Hide Gloves",
		wish3 = "Medallion of Steadfast Might (pass tank)",
	},
	{
		name  = "Zankz",
		class = "Unknown",
		wish1 = "Chronomirage",
		wish2 = "Personal Harm Prevention Field Emitter",
		wish3 = "Drake Fang Talisman",
	},
	{
		name  = "Zibazoo",
		class = "Unknown",
		wish1 = "Band of Accuria (Tazdingi)",
		wish2 = "Ring of Suffering (Tazdingi)",
		wish3 = "Shadowstrike (Tazdingi)",
	},
}
